### ISSUE TITLE
隐藏用户的电子邮件地址

### ISSUE THREAD

**Issue by ntzyz** [cnCalc/serainTalk#11]
如题，在进行账户迁移等操作时可以直接看到邮件地址，我们需要隐藏邮箱的部分要素，例如 `ntzyz@live.cn` 转为 `n***z@l**.cn`

**Comment by ntzyz** [comment]
补充一下需求，需要根据用户设置选择性的对部分用户不进行隐藏：

1. 对自己不隐藏
2. 设置为允许站内用户查看，且目前访问的请求来自已登录的账户

**Comment by kasora** [comment]
`/api/v1/member?name=xxx` 失效

**Comment by kasora** [comment]
原因是设计中匿名用户看不到email字段，现在已经解除改限制，匿名用户可以看到打码的email
