### ISSUE TITLE
彻底删除用户

### ISSUE THREAD

**Issue by zephray** [cnCalc/serainTalk#12]
需要能够提供接口彻底删除一个用户（如广告机）的profile以及相关发帖

**Comment by zephray** [comment]
![photo_2019-01-03_11-14-38](https://user-images.githubusercontent.com/5101637/50648739-f6411380-0f49-11e9-9c32-0486d3a4c16c.jpg)

**Comment by kasora** [comment]
- 广告机一般不会回复讨论串，而是直接新增讨论串
- 回复的逻辑设计时是基于 `回复不会被删除` 的前提，所以删除回复会影响正常发帖

所以针对广告机的处理逻辑是否可以变更为
- 广告机创建的讨论串会被直接删除
- 广告机的跟帖会被标记为封禁，但是仍然留存占用楼位。

**Comment by ntzyz** [comment]
Implemented in b43145be05440357b6ac7e89ee47d20d8fe5c651
