### ISSUE TITLE
[TODO] Use vue server side rendering

### ISSUE THREAD

**Issue by zephray** [cnCalc/serainTalk#4]

**Comment by ntzyz** [comment]
服务端渲染的适配工作已经基本完成，不过仍然有很多需要调整的地方：

1. 从首页/分区进入帖子时网站标题卡死在 Loading - xxx
2. 所有的加载指示器（loading-icon）需要检查
3. WebSocket 和 WsEventBus 处于无法使用的状态
4. 去除调试期间残留下来的大量 `console.log`

目前遇到的就是这些，随时补充。
