### ISSUE TITLE
[TODO] rebuild

### ISSUE THREAD

**Issue by kasora** [cnCalc/serainTalk#5]
- 阅读体验
  - 逻辑
    - 根据与路由严格对应的文件层级找到 handler
    - 在 handler 的定义前后能够找到整个链路所使用的 middleware/schema
  - 问题
    - RESTful 风格需要实现多个路由导向同一个 handler。导致文件层级与路由不能严格对应
    - 无法严格定义路由加载顺序，例如 `/a/:id` 若在 `/a/status` 之前加载，则会导致路由失效
    - 文件层级对应路由在多层嵌套时文件结构相当不友好
    - schema 中的抽象封装无法直接在上下文中体现出来
    - 阅读 services 代码依赖跳转
  - 解决方案
    - 文件层级与路由不一一对应。handler 由全局搜索路由得到
    - 路由链路配置在 handler 前后并写入 handler 函数对象，使用模块迭代器导入所有路由
    - 手动实现路由加载器，优先加载 路径短的 && 不包含:id的 路由
    - 文件系统的层级嵌套只保留一层，路由层级并排堆砌
    - schema 层不做展开，保证封装的 schema 尽可能语义化, joi 的错误作为返回值的一部分，以 `reason` 字段传递给前端
    - services 层与 handler 层目录严格对应
- 开发体验
  - 逻辑
    - services 层的抽象使用面向对象的方式
    - 使用 `$` 标记全局通用的对象名称
  - 问题
    - services 对象的生成方式
  - 解决方案
    - services 对象使用 (`req`, `res`) 生成
    - services 对象只将 `req.body` / `req.query` / `req.params` / `req.member` 缓存在对象中
    - services 对象提供 `data` 字段 `data = Object.assign(query, body, params)`
    - services 对象提供 `status` 和 `output` 字段， 使用 `send` 方法调用 `res.status(this.status).send(this.output)`。`output` 默认值为 `{ status: 'ok' }`

**Comment by ntzyz** [comment]
目前优先进行功能实现，这部分内容也需要重新讨论，暂时关闭 issue
